In [2]:
import numpy as np

x = np.array([1,2,3])
print(x.__class__)
print(x.shape)

print(x.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [5]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
print(W + X)

print(W * X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


In [6]:
A = np.array([[1,2],[3,4]])
print(A*10)

[[10 20]
 [30 40]]


In [7]:
A = np.array([[1,2],[3,4]])
b = np.array([10,20])

A * b

array([[10, 40],
       [30, 80]])

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.matmul(A,B))

32
[[19 22]
 [43 50]]


In [10]:
import numpy as np

W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10,2)
h = np.matmul(x,W1) +b1

In [11]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [12]:
x = np.random.randn(10,2)
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

h = np.matmul(x, W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2

In [13]:
class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))
    
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
    
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + B
        return out

In [14]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

    W1 = np.random.randn(1, H)
    b1 = np.random.randn(H)
    W2 = np.random.randn(H, O)
    b2 = np.random.randn(O)

    self.layers = [
        Affine(W1, b1),
        Sigmoid(),
        Affine(W2, b2)
    ]

    self.params = []
    for layer in self.layers:
        self.params += layers.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return X
    


NameError: name 'H' is not defined

In [15]:
import numpy as np
D, N = 8,7
x = np.random.randn(1, D)
y = np.repeat(x, N, axis = 0)
dy = np.random.randn(N, D)
dx = np.sum(dy, axis = 0, keepdims = True)

In [17]:
import numpy as np
D, N = 8,7
x = np.random.randn(N, D)
y = np.sum(x, axis = 0, keepdims = True)
dy = np.random.randn(1, D)
dx = np.repeat(dy, N, axis = 0)

In [ ]:
class MatMul:
    